### ISSUE TITLE
New version of Mongoose

### ISSUE THREAD

**Issue by Notaduck** [theoutlander/rest-api-workshop#1]
Hi. First of all, thanks for the great tutorial!! I just wanted to let you know that mongoose has been updated and I had to make some minor changes in order to make the code work. The file I'm talking about is the `src/models/customer.model.js`
You should change the `mongoose.conntect(....)` to 
```
mongoose.connect(`mongodb://${user}:${passwd}@${server}:${port}/${db}`, {'useNewUrlParser': true})
```
And then add the following line below
```
mongoose.set('useCreateIndex', true);
```

**Comment by theoutlander** [comment]
Thank you for the update @notaduck! Could you please send a PR? I can just merge it directly in that case.

**Comment by Notaduck** [comment]
@theoutlander you have seen the PR right?

**Comment by theoutlander** [comment]
Sorry @notaduck, I've been super busy and this fell through the cracks.
